defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.ckpt_dir}
  filename: "epoch={epoch}-val_loss={val/loss:.4f}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: -1

early_stopping:
  monitor: "val/loss"
  patience: 5
  mode: "min"

model_summary:
  max_depth: -1
